'use strict';
let token='',registered=false,busy=false;
const $=id=>document.getElementById(id);
const bytes=value=>Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
const encoded=value=>btoa(String.fromCharCode(...new Uint8Array(value))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
function controls(){$('register').disabled=busy||registered;$('login').disabled=busy||!registered;}
async function request(path,data){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-MINI-Token':token},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error);return result;}
function options(json,creating){const p=json.publicKey;p.challenge=bytes(p.challenge);if(creating)p.user.id=bytes(p.user.id);for(const name of ['allowCredentials','excludeCredentials'])if(p[name])p[name]=p[name].map(c=>({...c,id:bytes(c.id)}));return {publicKey:p};}
function result(c){const r=c.response;return {id:c.id,rawId:encoded(c.rawId),type:c.type,authenticatorAttachment:c.authenticatorAttachment,response:{clientDataJSON:encoded(r.clientDataJSON),...(r.attestationObject?{attestationObject:encoded(r.attestationObject)}:{authenticatorData:encoded(r.authenticatorData),signature:encoded(r.signature),userHandle:r.userHandle?encoded(r.userHandle):null})},clientExtensionResults:c.getClientExtensionResults()};}
async function action(creating){busy=true;controls();$('symbol').className='symbol busy';$('symbol').textContent='';$('status').textContent='请在系统提示中选择安全密钥，再触摸 MINI。';try{const kind=creating?'register':'login';const opt=await request(`/api/${kind}/begin`,{});const c=await navigator.credentials[creating?'create':'get'](options(opt,creating));const verified=await request(`/api/${kind}/complete`,result(c));registered=true;$('symbol').className='symbol success';$('symbol').textContent='✓';$('status').textContent=creating?'注册成功，可以进行触摸登录。':'登录成功，服务端签名验证通过。';$('counter').textContent=`签名计数器：${verified.counter}`;}catch(error){$('symbol').className='symbol error';$('symbol').textContent='×';$('status').textContent=`${error.name}: ${error.message}`;}finally{busy=false;controls();}}
$('register').addEventListener('click',()=>action(true));$('login').addEventListener('click',()=>action(false));
(async()=>{try{if(!window.isSecureContext||!navigator.credentials)throw Error('请用浏览器打开 http://localhost:8765');const state=await (await fetch('/api/state')).json();token=state.token;registered=state.registered;$('status').textContent=registered?'测试凭据已保存，请触摸登录。':'准备就绪，请先注册测试密钥。';if(registered)$('counter').textContent=`上次签名计数器：${state.counter}`;controls();}catch(error){$('status').textContent=error.message;}})();
